version: '3.8'

volumes:
  pg_data:
  alembic:

services:
  backend:
    build: .
    env_file: .env
    volumes:
      - alembic:/app/alembic
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-container-stock
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


