version: '3.8'

volumes:
  pg_data:
  alembic:

services:
  backend:
    build: .
    env_file: .env
    volumes:
      - .:/app
      - alembic:/app/alembic
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    container_name: postgres-container-stock
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    container_name: young-redis
    ports:
      - 6379:6379
  celery_worker:
    build: .
    container_name: young-celery-worker
    env_file: .env
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis