"""empty message

Revision ID: 944575b362dc
Revises: 1570cf5744da
Create Date: 2024-09-25 20:00:49.527721

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = '944575b362dc'
down_revision: Union[str, None] = '1570cf5744da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
